# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tempest.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(500, 552)
        MainWindow.setMinimumSize(QtCore.QSize(500, 552))
        MainWindow.setMaximumSize(QtCore.QSize(500, 552))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/User/.designer/backup/tempest.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 501, 531))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setObjectName("tabWidget")
        self.MLP = QtWidgets.QWidget()
        self.MLP.setObjectName("MLP")
        self.first_layer = QtWidgets.QSpinBox(self.MLP)
        self.first_layer.setGeometry(QtCore.QRect(250, 80, 42, 21))
        self.first_layer.setMinimum(100)
        self.first_layer.setMaximum(500)
        self.first_layer.setSingleStep(50)
        self.first_layer.setObjectName("first_layer")
        self.lineEdit = QtWidgets.QLineEdit(self.MLP)
        self.lineEdit.setGeometry(QtCore.QRect(30, 80, 201, 21))
        self.lineEdit.setWhatsThis("")
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setInputMask("")
        self.lineEdit.setFrame(False)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.MLP)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 120, 201, 21))
        self.lineEdit_2.setWhatsThis("")
        self.lineEdit_2.setAutoFillBackground(False)
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setFrame(False)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setDragEnabled(False)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.second_layer = QtWidgets.QSpinBox(self.MLP)
        self.second_layer.setEnabled(True)
        self.second_layer.setGeometry(QtCore.QRect(250, 120, 42, 21))
        self.second_layer.setReadOnly(False)
        self.second_layer.setAccelerated(False)
        self.second_layer.setMinimum(10)
        self.second_layer.setMaximum(50)
        self.second_layer.setSingleStep(5)
        self.second_layer.setObjectName("second_layer")
        self.third_layer = QtWidgets.QSpinBox(self.MLP)
        self.third_layer.setEnabled(False)
        self.third_layer.setGeometry(QtCore.QRect(250, 160, 42, 21))
        self.third_layer.setReadOnly(False)
        self.third_layer.setAccelerated(False)
        self.third_layer.setMinimum(10)
        self.third_layer.setMaximum(50)
        self.third_layer.setSingleStep(5)
        self.third_layer.setObjectName("third_layer")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.MLP)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 160, 201, 21))
        self.lineEdit_3.setWhatsThis("")
        self.lineEdit_3.setAutoFillBackground(False)
        self.lineEdit_3.setInputMask("")
        self.lineEdit_3.setFrame(False)
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_3.setDragEnabled(False)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.fourth_layer = QtWidgets.QSpinBox(self.MLP)
        self.fourth_layer.setEnabled(False)
        self.fourth_layer.setGeometry(QtCore.QRect(250, 200, 42, 21))
        self.fourth_layer.setReadOnly(False)
        self.fourth_layer.setAccelerated(False)
        self.fourth_layer.setMinimum(10)
        self.fourth_layer.setMaximum(50)
        self.fourth_layer.setSingleStep(5)
        self.fourth_layer.setObjectName("fourth_layer")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.MLP)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 200, 211, 21))
        self.lineEdit_4.setWhatsThis("")
        self.lineEdit_4.setAutoFillBackground(False)
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setFrame(False)
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_4.setDragEnabled(False)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.MLP)
        self.lineEdit_5.setGeometry(QtCore.QRect(30, 20, 201, 21))
        self.lineEdit_5.setWhatsThis("")
        self.lineEdit_5.setAutoFillBackground(False)
        self.lineEdit_5.setInputMask("")
        self.lineEdit_5.setFrame(False)
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_5.setDragEnabled(False)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.layer_preset = QtWidgets.QComboBox(self.MLP)
        self.layer_preset.setGeometry(QtCore.QRect(250, 20, 131, 22))
        self.layer_preset.setObjectName("layer_preset")
        self.layer_preset.addItem("")
        self.layer_preset.addItem("")
        self.layer_preset.addItem("")
        self.button_learning = QtWidgets.QPushButton(self.MLP)
        self.button_learning.setGeometry(QtCore.QRect(388, 420, 80, 23))
        self.button_learning.setObjectName("button_learning")
        self.log_NN = QtWidgets.QTextEdit(self.MLP)
        self.log_NN.setGeometry(QtCore.QRect(10, 360, 351, 81))
        self.log_NN.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.log_NN.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.log_NN.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.log_NN.setTabChangesFocus(False)
        self.log_NN.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.log_NN.setReadOnly(True)
        self.log_NN.setOverwriteMode(False)
        self.log_NN.setAcceptRichText(False)
        self.log_NN.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.log_NN.setObjectName("log_NN")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.MLP)
        self.lineEdit_6.setGeometry(QtCore.QRect(30, 250, 211, 21))
        self.lineEdit_6.setWhatsThis("")
        self.lineEdit_6.setAutoFillBackground(False)
        self.lineEdit_6.setInputMask("")
        self.lineEdit_6.setFrame(False)
        self.lineEdit_6.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_6.setDragEnabled(False)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.MLP)
        self.lineEdit_7.setGeometry(QtCore.QRect(30, 280, 211, 21))
        self.lineEdit_7.setWhatsThis("")
        self.lineEdit_7.setAutoFillBackground(False)
        self.lineEdit_7.setInputMask("")
        self.lineEdit_7.setFrame(False)
        self.lineEdit_7.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_7.setDragEnabled(False)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.solver = QtWidgets.QComboBox(self.MLP)
        self.solver.setGeometry(QtCore.QRect(250, 250, 211, 22))
        self.solver.setObjectName("solver")
        self.solver.addItem("")
        self.solver.addItem("")
        self.solver.addItem("")
        self.function = QtWidgets.QComboBox(self.MLP)
        self.function.setGeometry(QtCore.QRect(250, 280, 211, 22))
        self.function.setObjectName("function")
        self.function.addItem("")
        self.function.addItem("")
        self.function.addItem("")
        self.function.addItem("")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.MLP)
        self.lineEdit_8.setGeometry(QtCore.QRect(30, 310, 211, 21))
        self.lineEdit_8.setWhatsThis("")
        self.lineEdit_8.setAutoFillBackground(False)
        self.lineEdit_8.setInputMask("")
        self.lineEdit_8.setFrame(False)
        self.lineEdit_8.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_8.setDragEnabled(False)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.iteration = QtWidgets.QSpinBox(self.MLP)
        self.iteration.setEnabled(True)
        self.iteration.setGeometry(QtCore.QRect(250, 310, 61, 21))
        self.iteration.setAlignment(QtCore.Qt.AlignCenter)
        self.iteration.setReadOnly(False)
        self.iteration.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.iteration.setAccelerated(False)
        self.iteration.setMinimum(1000)
        self.iteration.setMaximum(10000)
        self.iteration.setSingleStep(1000)
        self.iteration.setObjectName("iteration")
        self.frame_2 = QtWidgets.QFrame(self.MLP)
        self.frame_2.setGeometry(QtCore.QRect(10, 450, 471, 41))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.name_NN = QtWidgets.QLineEdit(self.frame_2)
        self.name_NN.setEnabled(False)
        self.name_NN.setGeometry(QtCore.QRect(10, 10, 271, 20))
        self.name_NN.setReadOnly(True)
        self.name_NN.setObjectName("name_NN")
        self.load_NN = QtWidgets.QPushButton(self.frame_2)
        self.load_NN.setGeometry(QtCore.QRect(300, 10, 75, 23))
        self.load_NN.setObjectName("load_NN")
        self.save_NN = QtWidgets.QPushButton(self.frame_2)
        self.save_NN.setEnabled(False)
        self.save_NN.setGeometry(QtCore.QRect(380, 10, 75, 23))
        self.save_NN.setObjectName("save_NN")
        self.selection = QtWidgets.QComboBox(self.MLP)
        self.selection.setGeometry(QtCore.QRect(377, 380, 111, 22))
        self.selection.setObjectName("selection")
        self.selection.addItem("")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.MLP)
        self.lineEdit_10.setGeometry(QtCore.QRect(370, 350, 121, 21))
        self.lineEdit_10.setWhatsThis("")
        self.lineEdit_10.setAutoFillBackground(False)
        self.lineEdit_10.setInputMask("")
        self.lineEdit_10.setFrame(False)
        self.lineEdit_10.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setDragEnabled(False)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.tabWidget.addTab(self.MLP, "")
        self.Synth = QtWidgets.QWidget()
        self.Synth.setObjectName("Synth")
        self.list_massive = QtWidgets.QListWidget(self.Synth)
        self.list_massive.setGeometry(QtCore.QRect(10, 20, 191, 131))
        self.list_massive.setObjectName("list_massive")
        self.add_mass = QtWidgets.QPushButton(self.Synth)
        self.add_mass.setGeometry(QtCore.QRect(220, 20, 75, 23))
        self.add_mass.setObjectName("add_mass")
        self.delete_mass = QtWidgets.QPushButton(self.Synth)
        self.delete_mass.setEnabled(False)
        self.delete_mass.setGeometry(QtCore.QRect(220, 50, 75, 23))
        self.delete_mass.setObjectName("delete_mass")
        self.frame = QtWidgets.QFrame(self.Synth)
        self.frame.setGeometry(QtCore.QRect(10, 190, 221, 81))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_9.setEnabled(False)
        self.lineEdit_9.setGeometry(QtCore.QRect(5, 5, 171, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lineEdit_9.setPalette(palette)
        self.lineEdit_9.setFrame(False)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.range_mass = QtWidgets.QDoubleSpinBox(self.frame)
        self.range_mass.setEnabled(False)
        self.range_mass.setGeometry(QtCore.QRect(10, 40, 71, 22))
        self.range_mass.setAlignment(QtCore.Qt.AlignCenter)
        self.range_mass.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.range_mass.setPrefix("")
        self.range_mass.setDecimals(3)
        self.range_mass.setObjectName("range_mass")
        self.plot_mass = QtWidgets.QPushButton(self.frame)
        self.plot_mass.setEnabled(False)
        self.plot_mass.setGeometry(QtCore.QRect(100, 40, 111, 23))
        self.plot_mass.setObjectName("plot_mass")
        self.select_mass = QtWidgets.QPushButton(self.Synth)
        self.select_mass.setEnabled(False)
        self.select_mass.setGeometry(QtCore.QRect(210, 160, 75, 23))
        self.select_mass.setObjectName("select_mass")
        self.frame_3 = QtWidgets.QFrame(self.Synth)
        self.frame_3.setGeometry(QtCore.QRect(10, 360, 281, 131))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_11.setEnabled(False)
        self.lineEdit_11.setGeometry(QtCore.QRect(5, 5, 241, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lineEdit_11.setPalette(palette)
        self.lineEdit_11.setFrame(False)
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.get_efficiency = QtWidgets.QPushButton(self.frame_3)
        self.get_efficiency.setEnabled(False)
        self.get_efficiency.setGeometry(QtCore.QRect(10, 40, 211, 23))
        self.get_efficiency.setObjectName("get_efficiency")
        self.plot_efficiency = QtWidgets.QPushButton(self.frame_3)
        self.plot_efficiency.setEnabled(False)
        self.plot_efficiency.setGeometry(QtCore.QRect(10, 70, 211, 23))
        self.plot_efficiency.setObjectName("plot_efficiency")
        self.progressBar = QtWidgets.QProgressBar(self.frame_3)
        self.progressBar.setEnabled(False)
        self.progressBar.setGeometry(QtCore.QRect(10, 100, 261, 23))
        self.progressBar.setMaximum(2000)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.selected_tempest_2 = QtWidgets.QLineEdit(self.Synth)
        self.selected_tempest_2.setEnabled(False)
        self.selected_tempest_2.setGeometry(QtCore.QRect(10, 160, 191, 20))
        self.selected_tempest_2.setReadOnly(True)
        self.selected_tempest_2.setObjectName("selected_tempest_2")
        self.name_NN_2 = QtWidgets.QLineEdit(self.Synth)
        self.name_NN_2.setEnabled(False)
        self.name_NN_2.setGeometry(QtCore.QRect(10, 300, 281, 20))
        self.name_NN_2.setReadOnly(True)
        self.name_NN_2.setObjectName("name_NN_2")
        self.NN_for_massive = QtWidgets.QComboBox(self.Synth)
        self.NN_for_massive.setEnabled(False)
        self.NN_for_massive.setGeometry(QtCore.QRect(10, 330, 281, 22))
        self.NN_for_massive.setObjectName("NN_for_massive")
        self.NN_for_massive.addItem("")
        self.tabWidget.addTab(self.Synth, "")
        self.Tempest = QtWidgets.QWidget()
        self.Tempest.setObjectName("Tempest")
        self.list_tempest = QtWidgets.QListWidget(self.Tempest)
        self.list_tempest.setGeometry(QtCore.QRect(10, 10, 231, 191))
        self.list_tempest.setFrameShape(QtWidgets.QFrame.Box)
        self.list_tempest.setObjectName("list_tempest")
        self.picture = QtWidgets.QLabel(self.Tempest)
        self.picture.setEnabled(True)
        self.picture.setGeometry(QtCore.QRect(280, 10, 200, 190))
        self.picture.setText("")
        self.picture.setObjectName("picture")
        self.select_tempest = QtWidgets.QPushButton(self.Tempest)
        self.select_tempest.setEnabled(False)
        self.select_tempest.setGeometry(QtCore.QRect(10, 210, 75, 23))
        self.select_tempest.setObjectName("select_tempest")
        self.tempest_txt = QtWidgets.QTextEdit(self.Tempest)
        self.tempest_txt.setGeometry(QtCore.QRect(10, 250, 231, 241))
        self.tempest_txt.setReadOnly(True)
        self.tempest_txt.setObjectName("tempest_txt")
        self.selected_tempest = QtWidgets.QLineEdit(self.Tempest)
        self.selected_tempest.setEnabled(False)
        self.selected_tempest.setGeometry(QtCore.QRect(100, 210, 141, 20))
        self.selected_tempest.setReadOnly(True)
        self.selected_tempest.setObjectName("selected_tempest")
        self.line = QtWidgets.QFrame(self.Tempest)
        self.line.setGeometry(QtCore.QRect(262, 196, 240, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.Tempest)
        self.line_2.setGeometry(QtCore.QRect(243, 0, 41, 210))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Tempest)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(270, 250, 181, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.import_tempest = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.import_tempest.setEnabled(False)
        self.import_tempest.setObjectName("import_tempest")
        self.verticalLayout.addWidget(self.import_tempest)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.plot_tempest = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.plot_tempest.setEnabled(False)
        self.plot_tempest.setObjectName("plot_tempest")
        self.verticalLayout.addWidget(self.plot_tempest)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.process_nn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.process_nn.setEnabled(False)
        self.process_nn.setObjectName("process_nn")
        self.verticalLayout.addWidget(self.process_nn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.plot_processing = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.plot_processing.setEnabled(False)
        self.plot_processing.setObjectName("plot_processing")
        self.verticalLayout.addWidget(self.plot_processing)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.tabWidget.addTab(self.Tempest, "")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 530, 501, 21))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NNready = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.NNready.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.NNready.setPalette(palette)
        self.NNready.setShortcut("")
        self.NNready.setCheckable(True)
        self.NNready.setChecked(False)
        self.NNready.setAutoRepeat(True)
        self.NNready.setAutoExclusive(False)
        self.NNready.setObjectName("NNready")
        self.horizontalLayout.addWidget(self.NNready)
        self.massive = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.massive.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.massive.setPalette(palette)
        self.massive.setShortcut("")
        self.massive.setCheckable(True)
        self.massive.setChecked(False)
        self.massive.setAutoRepeat(True)
        self.massive.setAutoExclusive(False)
        self.massive.setObjectName("massive")
        self.horizontalLayout.addWidget(self.massive)
        self.massive_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.massive_2.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.massive_2.setPalette(palette)
        self.massive_2.setShortcut("")
        self.massive_2.setCheckable(True)
        self.massive_2.setChecked(False)
        self.massive_2.setAutoRepeat(True)
        self.massive_2.setAutoExclusive(False)
        self.massive_2.setObjectName("massive_2")
        self.horizontalLayout.addWidget(self.massive_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Neural Network for Tempest"))
        self.lineEdit.setText(_translate("MainWindow", "Количество нейронов в первом слое"))
        self.lineEdit_2.setText(_translate("MainWindow", "Количество нейронов в втором слое"))
        self.lineEdit_3.setText(_translate("MainWindow", "Количество нейронов в третьем слое"))
        self.lineEdit_4.setText(_translate("MainWindow", "Количество нейронов в четвертом слое"))
        self.lineEdit_5.setText(_translate("MainWindow", "Количество слоёв в нейронной сети"))
        self.layer_preset.setItemText(0, _translate("MainWindow", "Два слоя"))
        self.layer_preset.setItemText(1, _translate("MainWindow", "Три слоя"))
        self.layer_preset.setItemText(2, _translate("MainWindow", "Четыре слоя"))
        self.button_learning.setText(_translate("MainWindow", "Обучить"))
        self.log_NN.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.lineEdit_6.setText(_translate("MainWindow", "Метод решения нейронной сети"))
        self.lineEdit_7.setText(_translate("MainWindow", "Функция активации нейронной сети"))
        self.solver.setItemText(0, _translate("MainWindow", "Стохастический градиентный спуск"))
        self.solver.setItemText(1, _translate("MainWindow", "Квазиньютоновский метод"))
        self.solver.setItemText(2, _translate("MainWindow", "Adam"))
        self.function.setItemText(0, _translate("MainWindow", "Линейная"))
        self.function.setItemText(1, _translate("MainWindow", "Положительная линейная"))
        self.function.setItemText(2, _translate("MainWindow", "Сигмоидальная"))
        self.function.setItemText(3, _translate("MainWindow", "Тангенциальная"))
        self.lineEdit_8.setText(_translate("MainWindow", "Количество итераций"))
        self.load_NN.setText(_translate("MainWindow", "Загрузить"))
        self.save_NN.setText(_translate("MainWindow", "Сохранить"))
        self.selection.setItemText(0, _translate("MainWindow", "Универсальная"))
        self.lineEdit_10.setText(_translate("MainWindow", "Обучающая выборка:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MLP), _translate("MainWindow", "MLP"))
        self.add_mass.setText(_translate("MainWindow", "Добавить"))
        self.delete_mass.setText(_translate("MainWindow", "Удалить"))
        self.lineEdit_9.setText(_translate("MainWindow", "Построение сигнала из массива"))
        self.range_mass.setSuffix(_translate("MainWindow", " dB"))
        self.plot_mass.setText(_translate("MainWindow", "Построить график"))
        self.select_mass.setText(_translate("MainWindow", "Закрепить"))
        self.lineEdit_11.setText(_translate("MainWindow", "Эффективность построенной нейронной сети"))
        self.get_efficiency.setText(_translate("MainWindow", "Пересчитать на выбранном массиве"))
        self.plot_efficiency.setText(_translate("MainWindow", "Построить"))
        self.NN_for_massive.setItemText(0, _translate("MainWindow", "<Новая оценка>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Synth), _translate("MainWindow", "Synth"))
        self.select_tempest.setText(_translate("MainWindow", "Закрепить"))
        self.import_tempest.setText(_translate("MainWindow", "Импорт сигнала"))
        self.plot_tempest.setText(_translate("MainWindow", "Построить график"))
        self.process_nn.setText(_translate("MainWindow", "Обработать с помощью НС"))
        self.plot_processing.setText(_translate("MainWindow", "Построить обработанный график"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tempest), _translate("MainWindow", "Tempest"))
        self.NNready.setText(_translate("MainWindow", "Нейронная сеть обучена"))
        self.massive.setText(_translate("MainWindow", "Искусственный массив выбран"))
        self.massive_2.setText(_translate("MainWindow", "Реальный массив выбран"))

